server:
  port: ${PORT:8080}

app:
  title: Example Application
  version: 1.0

autumn:
  config-class-path: org.example.autumn.app.AutumnAppConfiguration
  datasource:
    url: jdbc:sqlite:app.db
    username: sa
    password:
    auto-commit: ${AUTO_COMMIT:false}
    driver-class-name: org.sqlite.JDBC
  db-template:
    entity-package-path: org.example.autumn.app.entity
